import fs from 'node:fs';
import path from 'node:path';

const sourceCases = [
  {
    slug: 'jagoinvestor-financial-platform',
    company: 'Jagoinvestor',
    industry: 'Financial education',
    title: 'Building a More Accessible Financial Learning Platform for Jagoinvestor',
    excerpt: 'Jagoinvestor needed a responsive, scalable platform that could turn a large library of personal-finance guidance, calculators, and practical tools into a clear learning experience.',
    image: 'images/case-studies/photos/unique/jagoinvestor-financial-platform.webp',
    accent: '#0F766E',
    readingMinutes: 4,
    sourceUrl: 'https://www.diginnovators.com/case-studies/digital-financial-jagoinvestor/',
    content: `<div class="wp-block-columns"><div class="wp-block-column single-post-container"><div class="wp-block-buttons btntabs"><div class="wp-block-button"><a class="wp-block-button__link">Summary</a></div><div class="wp-block-button"><a class="wp-block-button__link">Overview</a></div><div class="wp-block-button"><a class="wp-block-button__link">Challenges</a></div><div class="wp-block-button"><a class="wp-block-button__link">Solution</a></div><div class="wp-block-button"><a class="wp-block-button__link">Results</a></div></div></div></div>
<div class="wp-block-columns" id="bgsection"><div class="wp-block-column single-post-container bgimg-main"><div class="wp-block-spacer" style="height:60px" aria-hidden="true"></div><h3 id="h-summary-tldr">Summary / TLDR</h3><p>Jagoinvestor has helped Indian audiences understand personal finance since 2008. Its digital platform needed to make a deep library of articles, calculators, guides, and learning resources approachable for people with very different levels of financial confidence.</p><p>The engagement brought design, development, quality assurance, and ongoing maintenance together around one goal: give readers a dependable place to learn, explore scenarios, and make better-informed financial decisions.</p><figure class="wp-block-image"><img src="images/case-studies/photos/unique/jagoinvestor-financial-platform.webp" alt="Financial learning dashboard and savings-planning interface concept" class="case-study-source-image" loading="lazy"></figure><div class="wp-block-spacer" style="height:50px" aria-hidden="true"></div></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="overviewBlock"><img class="case-client-logo" src="images/case-studies/logos/jagoinvestor-financial-platform.svg" alt="Jagoinvestor case study wordmark" loading="lazy"><h3>Overview</h3><p><strong>Jagoinvestor</strong> is a personal-finance education platform built to simplify complex money topics and help individuals work toward practical financial goals. The brief was to create a responsive, easy-to-manage website that could support frequent publishing while keeping tools and long-form guidance easy to discover.</p><h4>Services provided</h4><ul><li>Experience strategy and responsive interface design</li><li>CMS-based website development and content architecture</li><li>Financial calculator, resource, and search integration</li><li>Cross-device quality assurance and performance optimization</li><li>Security updates, backups, maintenance, and feature support</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="challengesBlock"><h3>Challenges</h3><ul><li><strong>Making complex tools feel simple:</strong> Financial calculators needed accurate processing without creating an intimidating experience for first-time users.</li><li><strong>Supporting many devices:</strong> Articles and interactive tools had to remain fast and usable across browsers, screen sizes, and connection conditions.</li><li><strong>Balancing depth with clarity:</strong> The platform needed to present detailed financial guidance through an understandable hierarchy and consistent visual language.</li><li><strong>Staying dependable over time:</strong> A high-volume publishing platform requires continuous security, backup, performance, and compatibility work.</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="solutionBlock"><h3>Solution</h3><p>The experience was organized around clear topic paths, prominent search, and reusable content patterns. Responsive layouts kept articles, infographics, and tools readable on mobile, while the CMS gave the editorial team direct control over publishing and updates.</p><ul><li>Integrated calculators and interactive guidance into the wider learning journey.</li><li>Used caching, image optimization, and cross-platform testing to protect performance.</li><li>Established a clear visual hierarchy for articles, topic hubs, and downloadable resources.</li><li>Added routine monitoring, recovery processes, security patches, and feedback-led improvements.</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="resultsBlock"><h3>Results</h3><p>The completed platform gave readers a clearer route into financial education and gave the Jagoinvestor team a maintainable foundation for ongoing growth.</p><ul><li>Easier discovery of articles, calculators, and practical planning resources</li><li>A consistent experience across desktop, tablet, and mobile</li><li>Search-friendly content structures that support wider online reach</li><li>A flexible CMS and maintenance process ready for new topics and features</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column cta-bottom"><div class="wp-block-columns"><div class="wp-block-column" style="flex-basis:66.66%"><p><strong>Planning a knowledge platform?</strong> Let’s make complex information easier to understand and act on.</p></div><div class="wp-block-column" style="flex-basis:33.33%"><div class="wp-block-button btnyellow"><a class="wp-block-button__link" href="contact.html">Let’s talk</a></div></div></div></div></div>`
  },
  {
    slug: 'vissco-connect-health-companion',
    company: 'Vissco Connect',
    industry: 'Healthcare technology',
    title: 'Creating a Connected Mobile Companion for Healthcare Professionals',
    excerpt: 'Vissco Connect brought exercises, assessments, clinical resources, community features, and order management into one maintainable mobile ecosystem for healthcare professionals.',
    image: 'images/case-studies/photos/unique/vissco-connect-health-companion.webp',
    accent: '#2563EB',
    readingMinutes: 5,
    sourceUrl: 'https://www.diginnovators.com/case-studies/vissco-connect-health-companion/',
    content: `<div class="wp-block-columns"><div class="wp-block-column single-post-container"><div class="wp-block-buttons btntabs"><div class="wp-block-button"><a class="wp-block-button__link">Summary</a></div><div class="wp-block-button"><a class="wp-block-button__link">Overview</a></div><div class="wp-block-button"><a class="wp-block-button__link">Challenges</a></div><div class="wp-block-button"><a class="wp-block-button__link">Solution</a></div><div class="wp-block-button"><a class="wp-block-button__link">Results</a></div></div></div></div>
<div class="wp-block-columns" id="bgsection"><div class="wp-block-column single-post-container bgimg-main"><div class="wp-block-spacer" style="height:60px" aria-hidden="true"></div><h3 id="h-summary-tldr">Summary / TLDR</h3><p>Vissco Connect is a mobile ecosystem created for healthcare professionals. It brings guided exercises, fitness assessments, yoga content, condition monitoring, articles, community features, templates, and order management into a single professional companion.</p><p>The work combined product design, application development, custom API integration, quality engineering, and sustained support so a broad feature set could remain coherent and dependable in everyday use.</p><figure class="wp-block-image"><img src="images/case-studies/photos/unique/vissco-connect-health-companion.webp" alt="Healthcare professional mobile companion interface concept" class="case-study-source-image" loading="lazy"></figure><div class="wp-block-spacer" style="height:50px" aria-hidden="true"></div></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="overviewBlock"><img class="case-client-logo" src="images/case-studies/logos/vissco-connect-health-companion.svg" alt="Vissco Connect case study wordmark" loading="lazy"><h3>Overview</h3><p>Developed with <strong>Vissco</strong>, an orthopedic and physiotherapy products company, Vissco Connect was designed to support doctors through a focused mobile experience. Beyond the initial build, the brief included ongoing optimization, policy compliance, and support across a changing device and dependency landscape.</p><h4>Services provided</h4><ul><li>Mobile product and interface design</li><li>Cross-platform application development</li><li>Custom API and messaging integration</li><li>Functional, compatibility, performance, and security testing</li><li>App-store release support and ongoing maintenance</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="challengesBlock"><h3>Challenges</h3><ul><li><strong>Interconnected feature set:</strong> Exercises, assessments, content, profiles, community tools, and orders all depended on shared state and data.</li><li><strong>Complex API behavior:</strong> Custom filtering and search fields needed predictable client-side handling.</li><li><strong>Long-term maintainability:</strong> Package conflicts, discontinued dependencies, and growing code complexity had to be managed carefully.</li><li><strong>Device-specific behavior:</strong> Camera access caused crashes on some Vivo devices and required hardware-level investigation.</li><li><strong>Release compliance:</strong> The application had to keep pace with Play Store and App Store policy requirements.</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="solutionBlock"><h3>Solution</h3><p>The application architecture used Redux-Saga to coordinate asynchronous work and shared state. Reusable, nested components kept the interface consistent while dedicated integration patterns handled custom API behavior.</p><ul><li>Separated feature responsibilities into reusable modules with clearer standards.</li><li>Refined search, filter, notification, chat, referral, and task-management flows through iterative prototypes.</li><li>Adjusted camera permissions and device handling to address manufacturer-specific crashes.</li><li>Tested dependency combinations, devices, and release builds against store requirements.</li><li>Introduced phased releases, monitoring, and user feedback loops for ongoing improvement.</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="resultsBlock"><h3>Results</h3><p>Vissco Connect emerged as a more cohesive professional health platform, bringing previously separate tasks into one accessible mobile experience.</p><ul><li>Simpler navigation across clinical resources, activities, communication, and orders</li><li>More consistent behavior across supported devices</li><li>A reusable component foundation for future modules</li><li>An ongoing support model for compatibility, policy, and performance updates</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column cta-bottom"><div class="wp-block-columns"><div class="wp-block-column" style="flex-basis:66.66%"><p><strong>Building a complex mobile product?</strong> Let’s turn connected workflows into one clear experience.</p></div><div class="wp-block-column" style="flex-basis:33.33%"><div class="wp-block-button btnyellow"><a class="wp-block-button__link" href="contact.html">Let’s talk</a></div></div></div></div></div>`
  },
  {
    slug: 'london-insurance-academy-lms',
    company: 'London Insurance Academy',
    industry: 'Professional education',
    title: 'Building a Flexible LMS for London Insurance Academy',
    excerpt: 'London Insurance Academy needed an accessible learning platform that could support varied content formats, assessments, learner progress, discussion, and a growing professional audience.',
    image: 'images/case-studies/photos/unique/london-insurance-academy-lms.webp',
    accent: '#6D28D9',
    readingMinutes: 4,
    sourceUrl: 'https://www.diginnovators.com/case-studies/lms-site-development-for-london-insurance-academy/',
    content: `<div class="wp-block-columns"><div class="wp-block-column single-post-container"><div class="wp-block-buttons btntabs"><div class="wp-block-button"><a class="wp-block-button__link">Summary</a></div><div class="wp-block-button"><a class="wp-block-button__link">Overview</a></div><div class="wp-block-button"><a class="wp-block-button__link">Challenges</a></div><div class="wp-block-button"><a class="wp-block-button__link">Solution</a></div><div class="wp-block-button"><a class="wp-block-button__link">Results</a></div></div></div></div>
<div class="wp-block-columns" id="bgsection"><div class="wp-block-column single-post-container bgimg-main"><div class="wp-block-spacer" style="height:60px" aria-hidden="true"></div><h3 id="h-summary-tldr">Summary / TLDR</h3><p>London Insurance Academy set out to extend specialist insurance education beyond traditional teaching formats. The goal was a modern learning management system that could make professional courses more accessible, engaging, and cost-effective.</p><p>The resulting platform combined a structured course experience with multimedia lessons, assessments, learner progress, discussion, and administration tools built to support future growth.</p><figure class="wp-block-image"><img src="images/case-studies/photos/unique/london-insurance-academy-lms.webp" alt="Professional learning management system interface concept" class="case-study-source-image" loading="lazy"></figure><div class="wp-block-spacer" style="height:50px" aria-hidden="true"></div></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="overviewBlock"><img class="case-client-logo" src="images/case-studies/logos/london-insurance-academy-lms.svg" alt="London Insurance Academy case study wordmark" loading="lazy"><h3>Overview</h3><p><strong>London Insurance Academy</strong> provides education and training for students and insurance professionals. Its LMS needed to serve different learning preferences while remaining intuitive for learners, instructors, and administrators.</p><h4>Services provided</h4><ul><li>Discovery, requirements, and learning-experience design</li><li>Responsive frontend and backend development</li><li>Course, assessment, discussion, and progress features</li><li>Role and content-management workflows</li><li>Quality assurance and launch support</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="challengesBlock"><h3>Challenges</h3><ul><li><strong>Different learning styles:</strong> Course delivery needed to support video, interactive modules, written content, and flexible learning paths.</li><li><strong>Growth without slowdown:</strong> The architecture had to accommodate more learners, courses, and resources while protecting responsiveness.</li><li><strong>Connected tools and data:</strong> Learning features, databases, and supporting services needed reliable interoperability.</li><li><strong>Inclusive access:</strong> The experience had to work across devices and support users with varied accessibility needs.</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="solutionBlock"><h3>Solution</h3><p>Discovery sessions mapped course structures, user roles, content formats, and assessment methods before the product was organized into a clear course and navigation model.</p><ul><li>Added video, interactive content, quizzes, and learner preferences to support multiple learning modes.</li><li>Introduced discussion forums and progress tracking to make learning more participatory and visible.</li><li>Created clear categorization and role-aware tools for learners, instructors, and administrators.</li><li>Used a scalable technical foundation that could expand with the academy’s catalog and audience.</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="resultsBlock"><h3>Results</h3><p>The LMS gave London Insurance Academy a practical digital foundation for delivering specialist education to a broader professional audience.</p><ul><li>Course access no longer limited by classroom location</li><li>A richer learning experience through multimedia and interaction</li><li>Clearer visibility into progress and course participation</li><li>A scalable base for additional courses, learners, and features</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column cta-bottom"><div class="wp-block-columns"><div class="wp-block-column" style="flex-basis:66.66%"><p><strong>Planning a learning platform?</strong> Let’s design it around learners and the teams who support them.</p></div><div class="wp-block-column" style="flex-basis:33.33%"><div class="wp-block-button btnyellow"><a class="wp-block-button__link" href="contact.html">Let’s talk</a></div></div></div></div></div>`
  },
  {
    slug: 'tata-technologies-app-design',
    company: 'Tata Technologies',
    industry: 'Engineering technology',
    title: 'Designing Two Enterprise Applications for Tata Technologies',
    excerpt: 'Tata Technologies needed two related applications to move from a distinctive early concept through repeated design iterations, coordinated releases, and a consistent enterprise experience.',
    image: 'images/case-studies/photos/unique/tata-technologies-app-design.webp',
    accent: '#1D4ED8',
    readingMinutes: 3,
    sourceUrl: 'https://www.diginnovators.com/case-studies/exploring-tata-technologies-app-design-journey-with-diginovators/',
    content: `<div class="wp-block-columns"><div class="wp-block-column single-post-container"><div class="wp-block-buttons btntabs"><div class="wp-block-button"><a class="wp-block-button__link">Summary</a></div><div class="wp-block-button"><a class="wp-block-button__link">Overview</a></div><div class="wp-block-button"><a class="wp-block-button__link">Challenges</a></div><div class="wp-block-button"><a class="wp-block-button__link">Solution</a></div><div class="wp-block-button"><a class="wp-block-button__link">Results</a></div></div></div></div>
<div class="wp-block-columns" id="bgsection"><div class="wp-block-column single-post-container bgimg-main"><div class="wp-block-spacer" style="height:60px" aria-hidden="true"></div><h3 id="h-summary-tldr">Summary / TLDR</h3><p>Tata Technologies needed two enterprise applications designed in parallel around an early concept that was unusual for the Indian market. The work demanded a shared experience language, careful coordination, and many rounds of review before release.</p><p>The design process translated complex engineering and operational needs into clearer mobile workflows while maintaining consistency across both products.</p><figure class="wp-block-image"><img src="images/case-studies/photos/unique/tata-technologies-app-design.webp" alt="Enterprise engineering applications and digital product interface concept" class="case-study-source-image" loading="lazy"></figure><div class="wp-block-spacer" style="height:50px" aria-hidden="true"></div></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="overviewBlock"><img class="case-client-logo" src="images/case-studies/logos/tata-technologies-app-design.svg" alt="Tata Technologies case study wordmark" loading="lazy"><h3>Overview</h3><p><strong>Tata Technologies</strong> is a global product engineering and digital services company serving automotive, industrial machinery, aerospace, and adjacent sectors. The application work sat within a broader mission to help manufacturers and their partners engineer, build, and operate better products.</p><h4>Services provided</h4><ul><li>Product discovery and workflow mapping</li><li>UX and interface design for two applications</li><li>Interactive prototyping and shared component design</li><li>Stakeholder review and iterative release support</li><li>Website performance and Core Web Vitals optimization</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="challengesBlock"><h3>Challenges</h3><ul><li><strong>A new product concept:</strong> The original idea did not have an established local pattern to copy, so key interactions needed to be explored and validated.</li><li><strong>Two products at once:</strong> Parallel design work increased the need for shared decisions, reusable components, and coordinated delivery.</li><li><strong>Complex stakeholder feedback:</strong> Multiple iterations and releases were required before the final direction was ready.</li><li><strong>Performance expectations:</strong> The wider digital experience also needed measurable improvements to speed and Core Web Vitals.</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="solutionBlock"><h3>Solution</h3><p>The team established a shared design language across both applications, then moved from high-priority workflows into interactive prototypes that made review and iteration concrete.</p><ul><li>Mapped users, tasks, approvals, and exception paths before visual design.</li><li>Created reusable patterns so the applications felt related without forcing identical workflows.</li><li>Used staged reviews and release cycles to resolve ambiguity early and steadily refine the experience.</li><li>Addressed website performance through a focused Core Web Vitals audit and optimization work.</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="resultsBlock"><h3>Results</h3><p>The engagement produced a more coherent experience across both applications and a practical system for carrying design decisions into future releases.</p><ul><li>A shared interface foundation across parallel products</li><li>Clearer workflows for complex engineering and operational tasks</li><li>Reduced design drift through reusable components and review checkpoints</li><li>A reported 50% improvement in website speed and performance after Core Web Vitals work</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column cta-bottom"><div class="wp-block-columns"><div class="wp-block-column" style="flex-basis:66.66%"><p><strong>Coordinating a complex product portfolio?</strong> Let’s create the shared system behind every experience.</p></div><div class="wp-block-column" style="flex-basis:33.33%"><div class="wp-block-button btnyellow"><a class="wp-block-button__link" href="contact.html">Let’s talk</a></div></div></div></div></div>`
  },
  {
    slug: 'vissco-digital-revamp',
    company: 'Vissco',
    industry: 'Consumer healthcare',
    title: 'Rebuilding Vissco’s Digital Product-Discovery Platform',
    excerpt: 'Vissco needed to replace its legacy website with a responsive WordPress platform that could organize more than 1,000 orthopedic products without sacrificing usability or search visibility.',
    image: 'images/case-studies/photos/unique/vissco-digital-revamp.webp',
    accent: '#0F766E',
    readingMinutes: 4,
    sourceUrl: 'https://www.diginnovators.com/case-studies/visscos-digital-revamp/',
    content: `<div class="wp-block-columns"><div class="wp-block-column single-post-container"><div class="wp-block-buttons btntabs"><div class="wp-block-button"><a class="wp-block-button__link">Summary</a></div><div class="wp-block-button"><a class="wp-block-button__link">Overview</a></div><div class="wp-block-button"><a class="wp-block-button__link">Challenges</a></div><div class="wp-block-button"><a class="wp-block-button__link">Solution</a></div><div class="wp-block-button"><a class="wp-block-button__link">Results</a></div></div></div></div>
<div class="wp-block-columns" id="bgsection"><div class="wp-block-column single-post-container bgimg-main"><div class="wp-block-spacer" style="height:60px" aria-hidden="true"></div><h3 id="h-summary-tldr">Summary / TLDR</h3><p>Vissco needed to replace an aging website with a modern business and product-information platform. The new experience had to organize more than 1,000 orthopedic solutions and mobility aids while remaining understandable to customers with different needs and levels of product knowledge.</p><p>The revamp combined strategy, responsive design, WordPress development, content migration, quality assurance, and ongoing support into one maintainable product-discovery platform.</p><figure class="wp-block-image"><img src="images/case-studies/photos/unique/vissco-digital-revamp.webp" alt="Orthopedic healthcare product catalog and responsive website concept" class="case-study-source-image" loading="lazy"></figure><div class="wp-block-spacer" style="height:50px" aria-hidden="true"></div></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="overviewBlock"><img class="case-client-logo" src="images/case-studies/logos/vissco-digital-revamp.svg" alt="Vissco case study wordmark" loading="lazy"><h3>Overview</h3><p><strong>Vissco</strong> manufactures orthopedic supports, mobility aids, and rehabilitation products. Its website needed to work as a comprehensive information and discovery destination—showing the range clearly, supporting research and educational content, and extending the brand beyond physical stores and traditional distribution.</p><h4>Services provided</h4><ul><li>Digital strategy and experience design</li><li>Responsive frontend and WordPress development</li><li>Product taxonomy, content migration, and SEO continuity</li><li>Cross-browser, functional, and usability testing</li><li>Maintenance, security updates, and feature support</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="challengesBlock"><h3>Challenges</h3><ul><li><strong>A catalog of 1,000+ products:</strong> Categories, specifications, and use cases needed a structure that did not overwhelm visitors.</li><li><strong>CMS migration without search loss:</strong> Content had to move to a new system while protecting established SEO value.</li><li><strong>Broad audience needs:</strong> The same platform had to support consumers, caregivers, professionals, and international visitors.</li><li><strong>Education as well as discovery:</strong> Product pages needed to sit alongside useful resources that build understanding and confidence.</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="solutionBlock"><h3>Solution</h3><p>The redesign began with navigation and user-flow strategy, then established a responsive visual system aligned with the healthcare brand. Product content was restructured around clearer categories and more informative detail pages.</p><ul><li>Created a scalable taxonomy and search-friendly product-page model.</li><li>Migrated and optimized existing content with redirects and SEO continuity in mind.</li><li>Added richer product information, educational resources, and clearer calls to action.</li><li>Validated forms, browsing, and responsive behavior across devices and browsers.</li><li>Established a maintenance rhythm for content, security, performance, and enhancements.</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="resultsBlock"><h3>Results</h3><p>The redesigned platform gave Vissco a stronger digital storefront for product education and discovery, with a foundation that could continue to expand alongside the catalog.</p><ul><li>Wider access to product information beyond physical retail locations</li><li>Clearer browsing across a large and technically varied catalog</li><li>More useful educational content around orthopedic care and product selection</li><li>A maintainable CMS that supports ongoing search, content, and feature work</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column cta-bottom"><div class="wp-block-columns"><div class="wp-block-column" style="flex-basis:66.66%"><p><strong>Modernizing a complex catalog?</strong> Let’s make every product easier to find, understand, and manage.</p></div><div class="wp-block-column" style="flex-basis:33.33%"><div class="wp-block-button btnyellow"><a class="wp-block-button__link" href="contact.html">Let’s talk</a></div></div></div></div></div>`
  },
  {
    slug: 'fitcentive-wellness-rewards',
    company: 'Fitcentive',
    industry: 'Digital wellness',
    title: 'Turning Healthy Habits into Shared Challenges with Fitcentive',
    excerpt: 'Fitcentive makes mental and physical wellness more social by combining wearable connectivity, group challenges, personalized health insights, accountability, and rewards in one mobile experience.',
    image: 'images/case-studies/photos/unique/fitcentive-wellness-rewards.webp',
    accent: '#0F8F92',
    readingMinutes: 4,
    sourceUrl: 'https://fitcentive.app/',
    liveUrl: 'https://fitcentive.app/',
    content: `<div class="wp-block-columns"><div class="wp-block-column single-post-container"><div class="wp-block-buttons btntabs"><div class="wp-block-button"><a class="wp-block-button__link">Summary</a></div><div class="wp-block-button"><a class="wp-block-button__link">Overview</a></div><div class="wp-block-button"><a class="wp-block-button__link">Challenges</a></div><div class="wp-block-button"><a class="wp-block-button__link">Solution</a></div><div class="wp-block-button"><a class="wp-block-button__link">Results</a></div></div></div></div>
<div class="wp-block-columns" id="bgsection"><div class="wp-block-column single-post-container bgimg-main"><div class="wp-block-spacer" style="height:60px" aria-hidden="true"></div><h3 id="h-summary-tldr">Summary / TLDR</h3><p>Fitcentive is a wellness platform that turns progress into a shared experience. Members connect a wearable device, join group challenges, follow personalized health insights, and work toward rewards alongside friends and teammates.</p><p>The product brings physical health, mental well-being, accountability, and incentives into one focused mobile journey designed to make healthier habits easier to understand and sustain.</p><figure class="wp-block-image"><img src="images/case-studies/photos/unique/fitcentive-wellness-rewards.webp" alt="Social wellness challenges, wearable insights, and rewards interface concept" class="case-study-source-image" loading="lazy"></figure><div class="wp-block-spacer" style="height:50px" aria-hidden="true"></div></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="overviewBlock"><img class="case-client-logo" src="images/case-studies/logos/fitcentive-wellness-rewards.svg" alt="Fitcentive case study wordmark" loading="lazy"><h3>Overview</h3><p><strong>Fitcentive</strong> approaches health as more than a step count. Its mobile experience combines group participation with real-time guidance across physical activity, mental well-being, cardiovascular fitness, and stress—then uses accountability and rewards to help turn short-term goals into repeatable habits.</p><h4>Product scope</h4><ul><li>Group wellness challenges and team accountability</li><li>Wearable-device connection and activity progress</li><li>Personalized health insights and real-time tips</li><li>Goal tracking, incentives, and reward experiences</li><li>A focused acquisition journey leading into the mobile app</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="challengesBlock"><h3>Challenges</h3><ul><li><strong>Making wellness feel holistic:</strong> The experience needed to look beyond a single activity metric and represent physical and mental well-being together.</li><li><strong>Balancing individual and team progress:</strong> Personal health data had to remain understandable while contributing to a motivating group challenge.</li><li><strong>Turning data into action:</strong> Wearable signals and health information needed to become simple, timely guidance rather than another dense dashboard.</li><li><strong>Keeping incentives credible:</strong> Goals and rewards had to feel connected to meaningful progress and long-term habit formation.</li><li><strong>Explaining the product quickly:</strong> The public website needed to communicate the challenge, insight, and reward loop in a compact journey.</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="solutionBlock"><h3>Solution</h3><p>The product is organized around a clear participation loop: connect, join, improve, and earn. Each stage gives members a visible next action while keeping individual progress connected to a wider community.</p><ul><li>Group challenges create shared goals and make accountability part of the experience.</li><li>Wearable connectivity reduces manual tracking and keeps progress current.</li><li>Personalized insights translate health signals into practical guidance.</li><li>Progress and rewards provide clear milestones without separating motivation from wellness.</li><li>The public experience uses direct product benefits and repeated download calls to action to shorten the path into the app.</li></ul><p><a href="https://fitcentive.app/" target="_blank" rel="noopener noreferrer">Visit the Fitcentive website</a></p></div></div>
<div class="wp-block-columns"><div class="wp-block-column single-post-container" id="resultsBlock"><h3>Results</h3><p>Fitcentive presents a concise wellness proposition built around community, insight, and incentives rather than isolated activity tracking.</p><ul><li>One experience for joining challenges and following team progress</li><li>Wearable-driven health information presented as understandable guidance</li><li>Clear connections between daily goals, accountability, and rewards</li><li>A product story that communicates the core value before app download</li></ul></div></div>
<div class="wp-block-columns"><div class="wp-block-column cta-bottom"><div class="wp-block-columns"><div class="wp-block-column" style="flex-basis:66.66%"><p><strong>Building a product that changes habits?</strong> Let’s make motivation, progress, and value visible at every step.</p></div><div class="wp-block-column" style="flex-basis:33.33%"><div class="wp-block-button btnyellow"><a class="wp-block-button__link" href="contact.html">Let’s talk</a></div></div></div></div></div>`
  }
];

function caseWordmark(caseStudy) {
  const initial = caseStudy.company.trim().charAt(0).toUpperCase();
  return `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="160" viewBox="0 0 720 160" role="img" aria-labelledby="title"><title id="title">${caseStudy.company} case study wordmark</title><rect x="24" y="36" width="88" height="88" rx="24" fill="${caseStudy.accent}"/><text x="68" y="96" text-anchor="middle" font-family="Inter,Arial,sans-serif" font-size="48" font-weight="750" fill="#fff">${initial}</text><text x="136" y="94" font-family="Inter,Arial,sans-serif" font-size="42" font-weight="750" letter-spacing="-1" fill="#101828">${caseStudy.company}</text><text x="138" y="122" font-family="Inter,Arial,sans-serif" font-size="14" font-weight="650" letter-spacing="2" fill="#667085">${caseStudy.industry.toUpperCase()}</text></svg>`;
}

export function buildSourceCaseStudies(root) {
  const logoDir = path.join(root, 'images', 'case-studies', 'logos');
  fs.mkdirSync(logoDir, { recursive: true });

  return sourceCases.map((caseStudy) => {
    const logo = `images/case-studies/logos/${caseStudy.slug}.svg`;
    fs.writeFileSync(path.join(root, logo), caseWordmark(caseStudy));
    return {
      ...caseStudy,
      logo,
      fictional: false,
      datePublished: '2026-07-22'
    };
  });
}
